#!/bin/bash -eu

script=$(readlink -f "${BASH_SOURCE[0]}")
directory=$(dirname "$script")
artifacts="artifacts/"

cd "$directory"
rm -rf "$artifacts"
git worktree prune
git worktree add --no-checkout -B gh-pages "$artifacts" origin/gh-pages
git -C "$artifacts" restore --staged .
emacs -Q --script publish.el

cd "$artifacts"
git add -A
git commit -m '.'
