#!/bin/bash -eu

directory=$(dirname $BASH_SOURCE)
artifacts="artifacts/"

cd "$directory"
rm -rf "$artifacts"
git worktree prune
git worktree add --no-checkout -B pages "$artifacts" origin/pages
git -C "$artifacts" restore --staged .
emacs -Q --script publish.el

cd "$artifacts"
git add -A
git commit -m '.'
