#+TITLE: Software Conferences in 2025
#+DATE: [2025-12-16]

Over the years I've watched several hundred software conference talks across
different video platforms. But actually visiting a conference is an expensive
endeavor not all employers want to finance. The trick? Try to get accepted to a
conference as a speaker and convince your employer to see this as a "free
training". This was the first year I tried to implement this "simple trick" and
to my surprise I got really lucky: Out of four conferences I submitted proposals
to, three accepted me as a speaker.

* Grazer Linuxtage
:PROPERTIES:
:CUSTOM_ID: linuxtage
:END:

https://www.linuxtage.at/en

This is a free community conference around open source that is being held every
year in Graz. I talked about what unexpected benefits fun hobby projects can
have. [[https://martin.leyrer.priv.at][Leyrer]] held a great workshop about how to do conference talks the evening
before my own talk. His session was fun and gave me a few last-minute hints.

Another great benefit was that most talks got recorded. I was happy with how my
talk turned out and I could use the recording in my other proposals to improve
my chances to get accepted to other conferences.

* DevOpsDays Graz
:PROPERTIES:
:CUSTOM_ID: devopsdays
:END:

https://www.devopsdays.at

The [[https://coding-community.at][Coding Comminuty Club Graz]] decided that we should finally have our very own
DevOpsDays and so they booted up this conference from scratch. I put together a
unit-testing workshop in which we redesigned a small console application to make
it testable in a nice and easy way. But my absolute favorite moment was the
speakers dinner where I set next to [[https://de.wikipedia.org/wiki/Maria_Eichlseder][Maria Eichlseder]]. I told her about my backup
tool and the cryptographic elements in it. I also confessed to her all the
mistakes I made and we ended up reviewing tiny pieces of code on my phone. It
ain't getting nerdier than that.

* DDC Cologne
:PROPERTIES:
:CUSTOM_ID: ddc
:END:

https://www.developer-world.de/ddc

This was my biggest "catch" by far. DDC is a well known .NET conference in
Germany and I had the honor to do the same testing workshop I just mentioned
above, but in an extended fahsion. We had an open questions/discussions part at
the end of the workshop and I was surprised how knowledgable and interested the
participants were. At one point I was wondering why they chose my workshop
instead of some of the others, but I was told that it's sometimes nice to hear
"stuff you already know" from a potential different point of view. I appreciate
all the insights all of you gave me!

DDC was also the first conference I attended alone. While intimating at first, I
enjoyed speaking with participants, other speakers and of course the organizers
themselves.
