#+TITLE: Moonlander's Curse
#+DATE: [2025-01-21]

Five years ago I bought my very first mechanical keyboard, a [[https://www.zsa.io/moonlander][Moonlander Mark I]].
I didn't know anything about key switches so I bought them based on what sounded
best on a random review video on YouTube. I sometimes chuckle about that
decision making process but overall it worked out pretty well and I am happy
with my purchase. The only "problem" is that owning a fully customizable
keyboard is that it's fully customizable. Let me explain.

So the Moonlander can be configured using [[https://configure.zsa.io/][Oryx]], an online tool in which you can
specify which key should do what under which condition. You can find a decent
amount of layouts by using Oryx' search feature or by looking through entries on
[[https://people.zsa.io/][https://people.zsa.io/]] (such as [[https://configure.zsa.io/moonlander/layouts/rXlOQ/latest/0][mine]]). And this already outlines my point:
Having too many choices can be an issue on its own. I love my keyboard but in a
way I also hate it, because I can make it do anything that I can think of. Want
to simulate a mouse? Sure. Place your modifiers on the home row? Easy. Want to
create minimal setups using an endless amount of layers? Why not.

Tinkering with a keyboard layout comes with a lot of trial and error. You start
with a great idea, you flash your keyboard and then one hour later you realize
that your design is flawed and that you can't type something that you need on a
daily basis. Different "use cases" (e.g. programming, gaming or writing) might
make you believe that you need different layers/layouts for these tasks, but
then again: Are you actually improving your typing experience, or are you
overthinking something "simple"? That's the Moonlander's curse. I keep telling
myself that my current configuration is good enough, but every couple of months
my brain ponders the "but what if..." question. Be warned friends. Be warned.
